float32 center_x  # the orizontal coordinate of the object center (image frame)
float32 center_y  # the vertical coordinate of the object center (image frame)
float32 width     # the width of the object (image frame)
float32 height    # the height of the object (image frame)
string label      # the label of the object (image frame)
float32 x1
float32 y1
float32 x2
float32 y2
float32 x3
float32 y3
float32 x4
float32 y4